FROM docker.io/lsampaioweb/java-build:{jdk}-maven-alpine.{alpine}-{date} AS builder
# FROM docker.io/lsampaioweb/java-build:{jdk}-maven-alpine.{alpine}-latest AS builder
# FROM docker.io/lsampaioweb/java-build:latest AS builder

COPY . .

RUN --mount=type=cache,target=/root/.m2 \
  mvn clean package

FROM docker.io/lsampaioweb/java-web:{jdk}-alpine.{alpine}-{date} AS runtime
# FROM docker.io/lsampaioweb/java-web:{jdk}-alpine.{alpine}-latest AS runtime
# FROM docker.io/lsampaioweb/java-web:latest AS runtime

COPY --from=builder --chown=${APP_USER_NAME}:${APP_GROUP_NAME} ${APP_HOME}/target/*.jar app.jar

ENV JAVA_TOOL_OPTIONS=""

EXPOSE 8080 9443

ENTRYPOINT ["java", "-jar", "app.jar"]
