server:
  port: 8080
  error:
    include-stacktrace: "always"

management:
  endpoint:
    health:
      show-details: "always"

# Include only when OpenAPI is part of the project scope.
springdoc:
  swagger-ui:
    enabled: true
