server:
  port: 9443
  error:
    include-stacktrace: "never"

management:
  endpoint:
    health:
      show-details: "never"

# Include only when OpenAPI is part of the project scope.
springdoc:
  swagger-ui:
    enabled: false
